### ISSUE TITLE
Cippa Lippa

### ISSUE THREAD

**Issue by voxsim** [voxsim/minimalist-php-framework#1]

**Comment by fain182** [comment]
Una issue piena di senso direi :+1:

**Comment by voxsim** [comment]
Ahahahha provavamo zube.io, conosci?

**Comment by fain182** [comment]
ehehehe no, io avevo visto https://waffle.io ma non mi pareva fosse ai livelli di trello.. però non mi ricordo cosa non mi piaceva..
